"""rename department

Revision ID: 828618a6d195
Revises: b64e1ea85be4
Create Date: 2024-08-26 14:20:25.410218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828618a6d195'
down_revision = 'b64e1ea85be4'
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.rename_table('department', 'departments')
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('name', sa.String(), nullable=False),
#     sa.Column('address', sa.String(), nullable=True),
#     sa.PrimaryKeyConstraint('id')
    
#     op.drop_table('department')
#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.rename_table('departments', 'department')
#     sa.Column('id', sa.INTEGER(), nullable=False),
#     sa.Column('name', sa.VARCHAR(), nullable=False),
#     sa.Column('address', sa.VARCHAR(), nullable=True),
#     sa.PrimaryKeyConstraint('id')
    
#     op.drop_table('departments')
#     # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
